### ISSUE TITLE
shellscriptloader-0.1.1.sh

### ISSUE THREAD

**Issue by rowlandwatkins** [jaagr/shellscripts#1]
Hi,

So bootstrap.sh contains:

`
source shellscriptloader-0.1.1.sh
`

which doesn't appear in the shellscripts repo. But there is a set of similar scripts in contrib:

`
contrib/shellscriptloader-0.1.1/loader.sh
`

I tried using loader.sh as a replacement in bootstrap.sh, but received an error when loading:

`
loader: loader_include_loop(): found file not readable: $shellscripts_home/utils/log.sh
`

Is loader.sh a good replacement or could my placing of the shellscripts on my PATH be broken? Any hints appreciated!

Cheers,

Rowland

**Comment by eleanor-clifford** [comment]
I had the same problem when trying to use ```contrib/shellscriptloader-0.1.1/loader.sh```, but when I used ```contrib/shellscriptloader-0.1.1/loader.bash```, it worked fine.

**Comment by rowlandwatkins** [comment]
@tim-clifford Nice tip, thanks!
